#######################################################
###           applicationMonitoring with CSI        ###
#######################################################

apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  apiUrl: <api-URL>
  oneAgent:
    applicationMonitoring:
      useCSIDriver: true
  activeGate: # configuration applies to one AG instance
    capabilities:
      - routing
      - kubernetes-monitoring




