#######################################################
###           cloudNative                           ###
#######################################################

apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    alpha.operator.dynatrace.com/feature-automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: <apiURL>
  oneAgent:
    cloudNativeFullStack:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  activeGate: # configuration applies to one AG instance
    capabilities:
      - routing
      - kubernetes-monitoring
